version: '2'

services:
  kibana:
    image: kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  elasticsearch:
    image: elasticsearch
    command: elasticsearch -Des.network.bind_host=0.0.0.0

  metricbeat:
    build: .
    links:
      - elasticsearch
    pid: host
    environment:
      - SHIPPER_NAME=DOCKY
